-- 시퀀스 명 문법 :: SEQ_테이블명_ID
DROP SEQUENCE SEQ_USERS_ID;
CREATE SEQUENCE SEQ_USERS_ID start with 100;

DROP SEQUENCE SEQ_SHOP_ID;
CREATE SEQUENCE SEQ_SHOP_ID start with 100;

DROP SEQUENCE SEQ_SHOP_CATEGORY_ID;
CREATE SEQUENCE SEQ_SHOP_CATEGORY_ID start with 100;

DROP SEQUENCE SEQ_REVIEW_ID;
CREATE SEQUENCE SEQ_REVIEW_ID start with 100;

DROP SEQUENCE SEQ_FOLLOW_USER_ID;
CREATE SEQUENCE SEQ_FOLLOW_USER_ID start with 100;

DROP SEQUENCE SEQ_FOLLOW_CATEGORY_ID;
CREATE SEQUENCE SEQ_FOLLOW_CATEGORY_ID start with 100;

DROP SEQUENCE SEQ_REVIEW_COMMENT_ID;
CREATE SEQUENCE SEQ_REVIEW_COMMENT_ID start with 100;

DROP SEQUENCE SEQ_SHOP_CATEGORY_ID;
CREATE SEQUENCE SEQ_SHOP_CATEGORY_ID start with 100;

DROP SEQUENCE SEQ_EXHIBITIO_ID;
CREATE SEQUENCE SEQ_EXHIBITION_ID start with 100;

DROP SEQUENCE SEQ_PORTAL_DATA_ID;
CREATE SEQUENCE SEQ_PORTAL_DATA_ID start with 100;
