DROP SEQUENCE SEQ_SHOP_CATEGORY_ID;
CREATE SEQUENCE SEQ_SHOP_CATEGORY_ID start with 1;

TRUNCATE TABLE SHOP_CATEGORY;

Insert into MAP.SHOP_CATEGORY (CATEGORY_ID,CATEGORY_TITLE) values (SEQ_SHOP_CATEGORY_ID.NEXTVAL,'한식');
Insert into MAP.SHOP_CATEGORY (CATEGORY_ID,CATEGORY_TITLE) values (SEQ_SHOP_CATEGORY_ID.NEXTVAL,'일식');
Insert into MAP.SHOP_CATEGORY (CATEGORY_ID,CATEGORY_TITLE) values (SEQ_SHOP_CATEGORY_ID.NEXTVAL,'중식');
Insert into MAP.SHOP_CATEGORY (CATEGORY_ID,CATEGORY_TITLE) values (SEQ_SHOP_CATEGORY_ID.NEXTVAL,'미식');
Insert into MAP.SHOP_CATEGORY (CATEGORY_ID,CATEGORY_TITLE) values (SEQ_SHOP_CATEGORY_ID.NEXTVAL,'기타');